# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hotdemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for hotdemo
  pod 'Aspects'

  target 'hotdemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'hotdemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
